In [1]:
import os, sys
sys.path.append('../')

# 08 规则引擎模块 (core.rules)

提供规则定义、评估和报告功能。

**数据说明**: 基于 `hscredit_yyp.xlsx`

In [2]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

from hscredit import init_setting
from hscredit.core.rules import (
    Rule, get_columns_from_query, get_expr_variables,
    optimize_expr, beautify_expr,
)

init_setting()

# 加载数据
df = pd.read_excel('hscredit_yyp.xlsx')

# 构造目标变量
df['target'] = (df['MOB1'] > 3).astype(int)

# 重命名列为英文（pandas query 语法需要）
df = df.rename(columns={
    '中智小牛分C3': 'score_c3',
    '珊瑚92': 'score_coral',
    '极光欺诈分6v1': 'score_fraud',
    '青云24': 'score_qingyun',
    '占信V3': 'score_zhanxin'
})

print(f"样本数: {len(df):,}")
print(f"坏样本率: {df['target'].mean():.2%}")

样本数: 970
坏样本率: 16.70%

## 1. 基础规则定义

In [3]:
# 创建规则
rule1 = Rule(
    expr="score_c3 < 500 and score_coral > 80",
    name="高风险规则",
    description="信用分低且风险分高",
    weight=100
)

print(f"规则名称: {rule1.name}")
print(f"规则表达式: {rule1.expr}")
print(f"规则描述: {rule1.description}")
print(f"规则权重: {rule1.weight}")

# 从表达式中提取字段
columns = get_columns_from_query(rule1.expr)
print(f"\n涉及字段: {columns}")

规则名称: 高风险规则
规则表达式: score_c3 < 500 and score_coral > 80
规则描述: 信用分低且风险分高
规则权重: 100

涉及字段: ['score_c3', 'score_coral']

In [4]:
rule1 = Rule(
    expr="score_c3 < 500 & score_coral > 80"
)

rule2 = Rule(
    expr="score_c3 >= 0"
)

rule3 = Rule(
    expr="score_c5 >= 0 & score_c5 < 250"
)

rule4 = Rule(
    expr="score_c6 < 300"
)

rule5 = Rule(
    expr="score_c7 < 300"
)

In [5]:
rule1 | rule2 | (rule3 & (rule5 | rule4))

Rule('(score_c3 < 500 & score_coral > 80) | score_c3 >= 0 | (score_c5 >= 0 & score_c5 < 250 & score_c7 < 300) | score_c6 < 300')

In [6]:
# 全部逻辑运算符: & (与) / | (或) / ~ (非) / ^ (异或)
ra = Rule("score_c3 < 500", name="低分规则")
rb = Rule("score_coral > 80", name="高风险规则")

print("与   (a & b):", (ra & rb).expr)
print("或   (a | b):", (ra | rb).expr)
print("非   (~a)   :", (~ra).expr)
print("异或 (a ^ b):", (ra ^ rb).expr)

# 异或：命中其一但不同时命中两者
xor_rule = ra ^ rb
print()
print("异或规则命中样本数:", int(xor_rule.predict(df).sum()))

与   (a & b): score_c3 < 500 & score_coral > 80
或   (a | b): score_c3 < 500 | score_coral > 80
非   (~a)   : ~(score_c3 < 500)
异或 (a ^ b): ((score_c3 < 500) & ~(score_coral > 80)) | (~(score_c3 < 500) & (score_coral > 80))

异或规则命中样本数: 251

In [7]:
# 评估规则 - Rule 类直接使用 predict，无需 fit
result = rule1.predict(df)

print(f"命中规则样本数: {result.sum():,}")
print(f"规则命中率: {result.mean():.2%}")

# 查看命中样本的坏账率
hit_bad_rate = df[result]['target'].mean()
overall_bad_rate = df['target'].mean()
print(f"命中样本坏账率: {hit_bad_rate:.2%}")
print(f"总体坏账率: {overall_bad_rate:.2%}")
print(f"Lift: {hit_bad_rate/overall_bad_rate:.2f}")

命中规则样本数: 15
规则命中率: 1.55%
命中样本坏账率: 40.00%
总体坏账率: 16.70%
Lift: 2.40

In [8]:
# Rule 的数据操作方法: predict / result / filter，以及 get_expr_variables 提取变量
rule_demo = Rule("score_c3 < 500 and score_coral > 80", name="高风险规则")

# predict: 返回布尔 Series（命中=True）
mask = rule_demo.predict(df)
print(f"命中样本数: {int(mask.sum())} / {len(df)}")

# result: 复用上一次 predict 的结果（避免重复计算）
print(f"result() 与 predict() 一致: {(rule_demo.result() == mask).all()}")

# filter: 直接返回命中规则的子集 DataFrame
hit_df = rule_demo.filter(df)
print(f"filter 返回命中子集形状: {hit_df.shape}")

# get_expr_variables: 从表达式解析出涉及的字段名
print(f"表达式涉及字段: {get_expr_variables(rule_demo.expr)}")

命中样本数: 15 / 970
result() 与 predict() 一致: True
filter 返回命中子集形状: (15, 19)
表达式涉及字段: ['score_coral', 'score_c3']

In [9]:
# 优化和美化表达式
complex_expr = "((score_c3>=500) and (score_c3<=650)) or ((score_coral<500)and(score_fraud>0.6))"

print("原始表达式:")
print(complex_expr)

# 美化表达式
beautified = beautify_expr(complex_expr)
print("\n美化后表达式:")
print(beautified)

# 优化表达式
optimized = optimize_expr(complex_expr)
print("\n优化后表达式:")
print(optimized)

原始表达式:
((score_c3>=500) and (score_c3<=650)) or ((score_coral<500)and(score_fraud>0.6))

美化后表达式:
(score_c3 >= 500 & score_c3 <= 650) | (score_coral < 500 & score_fraud > 0.6)

优化后表达式:
(score_c3 >= 500 & score_c3 <= 650) | (score_coral < 500 & score_fraud > 0.6)

## 2. 规则组合

In [10]:
# 创建多个规则
rule_age = Rule(
    expr="score_c3 < 550",
    name="低分规则",
    weight=50
)

rule_risk = Rule(
    expr="score_coral > 80",
    name="高风险规则",
    weight=50
)

# AND 组合
combined_and = rule_age & rule_risk
result_and = combined_and.predict(df)
print(f"AND组合规则命中: {result_and.sum()} 条")

# OR 组合
combined_or = rule_age | rule_risk
result_or = combined_or.predict(df)
print(f"OR组合规则命中: {result_or.sum()} 条")

AND组合规则命中: 55 条
OR组合规则命中: 270 条

## 3. 规则有效性分析

In [11]:
# 分析多个规则的效果
rules = [
    Rule("score_c3 < 500", name="极低分规则", weight=100),
    Rule("score_coral > 85", name="极高风险规则", weight=80),
    Rule("score_fraud > 0.8", name="欺诈风险规则", weight=90)
]

results = []
for rule in rules:
    mask = rule.predict(df)
    hit_count = mask.sum()
    hit_rate = mask.mean()
    hit_bad_rate = df[mask]['target'].mean() if hit_count > 0 else 0
    overall_bad_rate = df['target'].mean()
    lift = hit_bad_rate / overall_bad_rate if overall_bad_rate > 0 else 0
    results.append({
        '规则名': rule.name,
        '命中率': f"{hit_rate:.2%}",
        '命中坏账率': f"{hit_bad_rate:.2%}",
        'Lift': f"{lift:.2f}",
        '权重': rule.weight
    })

results_df = pd.DataFrame(results)
print("=== 规则有效性分析 ===")
display(results_df)

=== 规则有效性分析 ===

      规则名     命中率   命中坏账率  Lift   权重
0   极低分规则   1.75%  35.29%  2.11  100
1  极高风险规则  27.22%  14.02%  0.84   80
2  欺诈风险规则   0.82%  37.50%  2.25   90

In [12]:
rule.report(df, target='target')

   规则分类               指标名称   分箱  样本总数   样本占比  好样本数  好样本占比  坏样本数  坏样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比    准确率    精确率    召回率   F1分数
0  验证规则  score_fraud > 0.8   命中     8 0.0082     5 0.0062     3 0.0185 0.3750 2.2454  0.0104  1.2557 0.8309 0.3750 0.0185 0.0353
1  验证规则  score_fraud > 0.8  未命中   962 0.9918   803 0.9938   159 0.9815 0.1653 0.9896 -1.2454 -1.2557 0.1691 0.1653 0.9815 0.2829

## 4. 规则策略文档表格转换 (`rule_strategy`)

将 `Rule.report` 的原始结果转换为策略文档常用的多层表、目标分析表和分组对比表。

In [13]:
from hscredit.report.rule_strategy import (
    rule_report_table,
    rule_target_analysis,
    rule_target_table,
    rule_group_hit_table,
)

# 基于已有规则生成单标签报告
report_single = rule1.report(df, target='target')
report_single.head()

   规则分类                               指标名称   分箱  样本总数   样本占比  好样本数  好样本占比  坏样本数  坏样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比    准确率    精确率    召回率   F1分数
0  验证规则  score_c3 < 500 & score_coral > 80   命中    15 0.0155     9 0.0111     6 0.0370 0.4000 2.3951  0.0219  1.4170 0.8299 0.4000 0.0370 0.0678
1  验证规则  score_c3 < 500 & score_coral > 80  未命中   955 0.9845   799 0.9889   156 0.9630 0.1634 0.9781 -1.3951 -1.4170 0.1701 0.1634 0.9630 0.2793

In [14]:
# 规则详情横向展开表（按逾期指标分列）
report_table = rule_report_table(report_single)
report_table

                                规则详情      target
                                规则名称   分箱   样本总数   样本占比   坏样本率  LIFT值
0  score_c3 < 500 & score_coral > 80   命中     15 0.0155 0.4000 2.3951
1  score_c3 < 500 & score_coral > 80  未命中    955 0.9845 0.1634 0.9781
2  score_c3 < 500 & score_coral > 80   合计    970 1.0000 0.1670 1.0000

In [15]:
# 规则目标分析表（需要提供执行策略前的当前通过率）
current_pass_rate = 0.45  # 示例：执行前通过率为 100%
target_analysis = rule_target_analysis(report_single, current_pass_rate=current_pass_rate)
target_analysis

  score_c3 < 500 & score_coral > 80   坏样本率               样本总数            样本占比   规则指标          绝对比例          相对比例
                               逾期指标     合计    未命中     命中   合计  未命中  命中     命中 拒绝LIFT  风险拒绝比   逾期改善    通过率   逾期改善    通过率
0                            target 0.1670 0.1634 0.4000  970  955  15 0.0155 2.3951 1.4170 0.0037 0.9845 0.0219 0.4430

In [16]:
# 规则、逾期指标和命中情况纵向明细表
target_detail = rule_target_table(report_single)
target_detail

                                规则详情    逾期指标 命中情况  样本总数   样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比
0  score_c3 < 500 & score_coral > 80  target   命中    15 0.0155 0.4000 2.3951  0.0219  1.4170
1  score_c3 < 500 & score_coral > 80  target  未命中   955 0.9845 0.1634 0.9781 -1.3951 -1.4170
2  score_c3 < 500 & score_coral > 80  target   合计   970 1.0000 0.1670 1.0000  0.0000  0.0000

In [17]:
# 多分组规则命中效果对比表（训练集 vs 验证集）
from sklearn.model_selection import train_test_split
_, valid_df = train_test_split(df, test_size=0.3, random_state=42)

valid_report = rule1.report(valid_df, target='target')
group_reports = {
    '训练集': report_single,
    '验证集': valid_report,
}
group_hit = rule_group_hit_table(group_reports)
group_hit

                                规则详情                坏样本率          样本占比        LIFT指标        样本总数
                                规则名称    逾期指标 是否命中    训练集    验证集    训练集    验证集    训练集    验证集  训练集  验证集
0  score_c3 < 500 & score_coral > 80  target   命中 0.4000 0.6667 0.0155 0.0103 2.3951 4.6190   15    3
1  score_c3 < 500 & score_coral > 80  target  未命中 0.1634 0.1389 0.9845 0.9897 0.9781 0.9623  955  288

### 4.1 多标签逾期分析

支持传入 `overdue` 与 `dpds` 生成多逾期标签策略表，再使用 `rule_strategy` 转换。

In [18]:
multi_report = rule1.report(
    df,
    target='target',
    overdue=['MOB1'],
    dpds=[7, 3, 0]
)
multi_report.head()

   分箱详情                                                     MOB1 7+                            ... MOB1 0+
   规则分类                               指标名称   分箱 样本总数   样本占比    好样本数  好样本占比 坏样本数  坏样本占比   坏样本率  ...    坏样本数  坏样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比    准确率    精确率    召回率   F1分数
0  验证规则  score_c3 < 500 & score_coral > 80   命中   15 0.0155       9 0.0109    6 0.0414 0.4000  ...       6 0.0302 0.4000 1.9497  0.0149  0.9647 0.7918 0.4000 0.0302 0.0561
1  验证规则  score_c3 < 500 & score_coral > 80  未命中  955 0.9845     816 0.9891  139 0.9586 0.1455  ...     193 0.9698 0.2021 0.9851 -0.9497 -0.9647 0.2082 0.2021 0.9698 0.3345

[2 rows x 41 columns]

In [19]:
# 多标签下的策略文档表
multi_target_table = rule_target_table(multi_report)
multi_target_table

                                规则详情     逾期指标 命中情况  样本总数   样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比
0  score_c3 < 500 & score_coral > 80  MOB1 7+   命中    15 0.0155 0.4000 2.6759  0.0263  1.7022
1  score_c3 < 500 & score_coral > 80  MOB1 7+  未命中   955 0.9845 0.1455 0.9737 -1.6759 -1.7022
2  score_c3 < 500 & score_coral > 80  MOB1 7+   合计   970 1.0000 0.1495 1.0000  0.0000  0.0000
3  score_c3 < 500 & score_coral > 80  MOB1 3+   命中    15 0.0155 0.4000 2.3951  0.0219  1.4170
4  score_c3 < 500 & score_coral > 80  MOB1 3+  未命中   955 0.9845 0.1634 0.9781 -1.3951 -1.4170
5  score_c3 < 500 & score_coral > 80  MOB1 3+   合计   970 1.0000 0.1670 1.0000  0.0000  0.0000
6  score_c3 < 500 & score_coral > 80  MOB1 0+   命中    15 0.0155 0.4000 1.9497  0.0149  0.9647
7  score_c3 < 500 & score_coral > 80  MOB1 0+  未命中   955 0.9845 0.2021 0.9851 -0.9497 -0.9647
8  score_c3 < 500 & score_coral > 80  MOB1 0+   合计   970 1.0000 0.2052 1.0000  0.0000  0.0000