In [1]:
import os, sys
sys.path.append('../')

# 08 规则引擎模块 (core.rules)

提供规则定义、评估和报告功能。

**数据说明**: 基于 `hscredit_yyp.xlsx`

In [2]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

from hscredit import init_setting
from hscredit.core.rules import (
    Rule, RuleFlow, get_columns_from_query, get_expr_variables,
    optimize_expr, beautify_expr,
)

init_setting()

# 加载数据
df = pd.read_excel('hscredit_yyp.xlsx')

# 构造目标变量
df['target'] = (df['MOB1'] > 3).astype(int)

# 重命名列为英文（pandas query 语法需要）
df = df.rename(columns={
    '中智小牛分C3': 'score_c3',
    '珊瑚92': 'score_coral',
    '极光欺诈分6v1': 'score_fraud',
    '青云24': 'score_qingyun',
    '占信V3': 'score_zhanxin'
})

print(f"样本数: {len(df):,}")
print(f"坏样本率: {df['target'].mean():.2%}")

样本数: 970
坏样本率: 16.70%

## 1. 基础规则定义

In [3]:
# 创建规则
rule1 = Rule(
    expr="score_c3 < 500 and score_coral > 80",
    name="高风险规则",
    description="信用分低且风险分高",
    weight=100
)

print(f"规则名称: {rule1.name}")
print(f"规则表达式: {rule1.expr}")
print(f"规则描述: {rule1.description}")
print(f"规则权重: {rule1.weight}")

# 从表达式中提取字段
columns = get_columns_from_query(rule1.expr)
print(f"\n涉及字段: {columns}")

规则名称: 高风险规则
规则表达式: score_c3 < 500 and score_coral > 80
规则描述: 信用分低且风险分高
规则权重: 100

涉及字段: ['score_c3', 'score_coral']

In [4]:
rule1 = Rule(
    expr="score_c3 < 500 & score_coral > 80"
)

rule2 = Rule(
    expr="score_c3 >= 0"
)

rule3 = Rule(
    expr="score_c5 >= 0 & score_c5 < 250"
)

rule4 = Rule(
    expr="score_c6 < 300"
)

rule5 = Rule(
    expr="score_c7 < 300"
)

In [5]:
rule1 | rule2 | (rule3 & (rule5 | rule4))

Rule('(score_c3 < 500 & score_coral > 80) | score_c3 >= 0 | (score_c5 >= 0 & score_c5 < 250 & (score_c7 < 300 | score_c6 < 300))')

In [6]:
# 全部逻辑运算符: & (与) / | (或) / ~ (非) / ^ (异或)
ra = Rule("score_c3 < 500", name="低分规则")
rb = Rule("score_coral > 80", name="高风险规则")

print("与   (a & b):", (ra & rb).expr)
print("或   (a | b):", (ra | rb).expr)
print("非   (~a)   :", (~ra).expr)
print("异或 (a ^ b):", (ra ^ rb).expr)

# 异或：命中其一但不同时命中两者
xor_rule = ra ^ rb
print()
print("异或规则命中样本数:", int(xor_rule.predict(df).sum()))

与   (a & b): score_c3 < 500 & score_coral > 80
或   (a | b): score_c3 < 500 | score_coral > 80
非   (~a)   : ~(score_c3 < 500)
异或 (a ^ b): (score_c3 < 500 & ~(score_coral > 80)) | (~(score_c3 < 500) & score_coral > 80)

异或规则命中样本数: 251

In [7]:
# 评估规则 - Rule 类直接使用 predict，无需 fit
result = rule1.predict(df)

print(f"命中规则样本数: {result.sum():,}")
print(f"规则命中率: {result.mean():.2%}")

# 查看命中样本的坏账率
hit_bad_rate = df[result]['target'].mean()
overall_bad_rate = df['target'].mean()
print(f"命中样本坏账率: {hit_bad_rate:.2%}")
print(f"总体坏账率: {overall_bad_rate:.2%}")
print(f"Lift: {hit_bad_rate/overall_bad_rate:.2f}")

命中规则样本数: 15
规则命中率: 1.55%
命中样本坏账率: 40.00%
总体坏账率: 16.70%
Lift: 2.40

In [8]:
# Rule 的数据操作方法: predict / result / filter，以及 get_expr_variables 提取变量
rule_demo = Rule("score_c3 < 500 and score_coral > 80", name="高风险规则")

# predict: 返回布尔 Series（命中=True）
mask = rule_demo.predict(df)
print(f"命中样本数: {int(mask.sum())} / {len(df)}")

# result: 复用上一次 predict 的结果（避免重复计算）
print(f"result() 与 predict() 一致: {(rule_demo.result() == mask).all()}")

# filter: 直接返回命中规则的子集 DataFrame
hit_df = rule_demo.filter(df)
print(f"filter 返回命中子集形状: {hit_df.shape}")

# get_expr_variables: 从表达式解析出涉及的字段名
print(f"表达式涉及字段: {get_expr_variables(rule_demo.expr)}")

命中样本数: 15 / 970
result() 与 predict() 一致: True
filter 返回命中子集形状: (15, 19)
表达式涉及字段: ['score_coral', 'score_c3']

In [9]:
# 优化和美化表达式
complex_expr = "((score_c3>=500) and (score_c3<=650)) or ((score_coral<500)and(score_fraud>0.6))"

print("原始表达式:")
print(complex_expr)

# 美化表达式
beautified = beautify_expr(complex_expr)
print("\n美化后表达式:")
print(beautified)

# 优化表达式
optimized = optimize_expr(complex_expr)
print("\n优化后表达式:")
print(optimized)

原始表达式:
((score_c3>=500) and (score_c3<=650)) or ((score_coral<500)and(score_fraud>0.6))

美化后表达式:
(score_c3 >= 500 & score_c3 <= 650) | (score_coral < 500 & score_fraud > 0.6)

优化后表达式:
(score_c3 >= 500 & score_c3 <= 650) | (score_coral < 500 & score_fraud > 0.6)

## 2. 规则组合

In [10]:
# 创建多个规则
rule_age = Rule(
    expr="score_c3 < 550",
    name="低分规则",
    weight=50
)

rule_risk = Rule(
    expr="score_coral > 80",
    name="高风险规则",
    weight=50
)

# AND 组合
combined_and = rule_age & rule_risk
result_and = combined_and.predict(df)
print(f"AND组合规则命中: {result_and.sum()} 条")

# OR 组合
combined_or = rule_age | rule_risk
result_or = combined_or.predict(df)
print(f"OR组合规则命中: {result_or.sum()} 条")

AND组合规则命中: 55 条
OR组合规则命中: 270 条

## 3. 规则有效性分析

In [11]:
# 分析多个规则的效果
rules = [
    Rule("score_c3 < 500", name="极低分规则", weight=100),
    Rule("score_coral > 85", name="极高风险规则", weight=80),
    Rule("score_fraud > 0.8", name="欺诈风险规则", weight=90)
]

results = []
for rule in rules:
    mask = rule.predict(df)
    hit_count = mask.sum()
    hit_rate = mask.mean()
    hit_bad_rate = df[mask]['target'].mean() if hit_count > 0 else 0
    overall_bad_rate = df['target'].mean()
    lift = hit_bad_rate / overall_bad_rate if overall_bad_rate > 0 else 0
    results.append({
        '规则名': rule.name,
        '命中率': f"{hit_rate:.2%}",
        '命中坏账率': f"{hit_bad_rate:.2%}",
        'Lift': f"{lift:.2f}",
        '权重': rule.weight
    })

results_df = pd.DataFrame(results)
print("=== 规则有效性分析 ===")
display(results_df)

=== 规则有效性分析 ===

      规则名     命中率   命中坏账率  Lift   权重
0   极低分规则   1.75%  35.29%  2.11  100
1  极高风险规则  27.22%  14.02%  0.84   80
2  欺诈风险规则   0.82%  37.50%  2.25   90

In [12]:
rule.report(df, target='target')

   规则分类               指标名称   分箱  样本总数   样本占比  好样本数  好样本占比  坏样本数  坏样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比    准确率    精确率    召回率   F1分数
0  验证规则  score_fraud > 0.8   命中     8 0.0082     5 0.0062     3 0.0185 0.3750 2.2454  0.0104  1.2557 0.8309 0.3750 0.0185 0.0353
1  验证规则  score_fraud > 0.8  未命中   962 0.9918   803 0.9938   159 0.9815 0.1653 0.9896 -1.2454 -1.2557 0.1691 0.1653 0.9815 0.2829

## 4. 规则策略文档表格转换 (`rule_strategy`)

将 `Rule.report` 的原始结果转换为策略文档常用的多层表、目标分析表和分组对比表。

In [13]:
from hscredit.report.rule_strategy import (
    rule_report_table,
    rule_target_analysis,
    rule_target_table,
    rule_group_hit_table,
    rule_group_compare,
)

# 基于已有规则生成单标签报告
report_single = rule1.report(df, target='target')
report_single.head()

   规则分类                               指标名称   分箱  样本总数   样本占比  好样本数  好样本占比  坏样本数  坏样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比    准确率    精确率    召回率   F1分数
0  验证规则  score_c3 < 500 & score_coral > 80   命中    15 0.0155     9 0.0111     6 0.0370 0.4000 2.3951  0.0219  1.4170 0.8299 0.4000 0.0370 0.0678
1  验证规则  score_c3 < 500 & score_coral > 80  未命中   955 0.9845   799 0.9889   156 0.9630 0.1634 0.9781 -1.3951 -1.4170 0.1701 0.1634 0.9630 0.2793

In [14]:
# 规则详情横向展开表（按逾期指标分列）
report_table = rule_report_table(report_single)
report_table

                                规则详情      target
                                规则名称   分箱   样本总数   样本占比   坏样本率  LIFT值
0  score_c3 < 500 & score_coral > 80   命中     15 0.0155 0.4000 2.3951
1  score_c3 < 500 & score_coral > 80  未命中    955 0.9845 0.1634 0.9781
2  score_c3 < 500 & score_coral > 80   合计    970 1.0000 0.1670 1.0000

In [15]:
# 规则目标分析表（需要提供执行策略前的当前通过率）
current_pass_rate = 0.45  # 示例：执行前通过率为 100%
target_analysis = rule_target_analysis(report_single, current_pass_rate=current_pass_rate)
target_analysis

  score_c3 < 500 & score_coral > 80   坏样本率               样本总数            样本占比   规则指标          绝对比例          相对比例
                               逾期指标     合计    未命中     命中   合计  未命中  命中     命中 拒绝LIFT  风险拒绝比   逾期改善    通过率   逾期改善    通过率
0                            target 0.1670 0.1634 0.4000  970  955  15 0.0155 2.3951 1.4170 0.0037 0.9845 0.0219 0.4430

In [16]:
# 规则、逾期指标和命中情况纵向明细表
target_detail = rule_target_table(report_single)
target_detail

                                规则详情    逾期指标 命中情况  样本总数   样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比
0  score_c3 < 500 & score_coral > 80  target   命中    15 0.0155 0.4000 2.3951  0.0219  1.4170
1  score_c3 < 500 & score_coral > 80  target  未命中   955 0.9845 0.1634 0.9781 -1.3951 -1.4170
2  score_c3 < 500 & score_coral > 80  target   合计   970 1.0000 0.1670 1.0000  0.0000  0.0000

In [17]:
# 多分组规则命中效果对比表（训练集 vs 验证集）
from sklearn.model_selection import train_test_split
_, valid_df = train_test_split(df, test_size=0.3, random_state=42)

valid_report = rule1.report(valid_df, target='target')
group_reports = {
    '训练集': report_single,
    '验证集': valid_report,
}
group_hit = rule_group_hit_table(group_reports)
group_hit

                                规则详情                坏样本率          样本占比        LIFT指标        样本总数
                                规则名称    逾期指标 是否命中    训练集    验证集    训练集    验证集    训练集    验证集  训练集  验证集
0  score_c3 < 500 & score_coral > 80  target   命中 0.4000 0.6667 0.0155 0.0103 2.3951 4.6190   15    3
1  score_c3 < 500 & score_coral > 80  target  未命中 0.1634 0.1389 0.9845 0.9897 0.9781 0.9623  955  288

In [18]:
# C. 多标签口径：overdue + dpds 组合，按放款月份对比同一规则在各 DPD 定义下的效果
multi_compare = rule_group_compare(
    df,
    rule1,                       # 也可直接传表达式字符串
    date_col='放款时间', freq='M',
    overdue=['MOB1'], dpds=[7, 3, 0],
    rule_name='高风险规则',
)
multi_compare

    规则详情                  坏样本率                            样本占比                          LIFT指标                            样本总数
    规则名称     逾期指标 是否命中 2025-11 2025-12 2026-01 2026-02 2025-11 2025-12 2026-01 2026-02 2025-11 2025-12 2026-01 2026-02 2025-11 2025-12 2026-01 2026-02
0  高风险规则  MOB1 7+   命中  0.0000  0.0000  0.8333  0.2000  0.0000  0.0142  0.0395  0.0276  0.0000  0.0000  4.3678  2.1294       0       4       6       5
1  高风险规则  MOB1 7+  未命中  0.1545  0.1588  0.1644  0.0909  1.0000  0.9858  0.9605  0.9724  1.0000  1.0144  0.8616  0.9679     356     277     146     176
2  高风险规则  MOB1 3+   命中  0.0000  0.0000  0.8333  0.2000  0.0000  0.0142  0.0395  0.0276  0.0000  0.0000  4.2222  1.2929       0       4       6       5
3  高风险规则  MOB1 3+  未命中  0.1573  0.1733  0.1712  0.1534  1.0000  0.9858  0.9605  0.9724  1.0000  1.0144  0.8676  0.9917     356     277     146     176
4  高风险规则  MOB1 0+   命中  0.0000  0.0000  0.8333  0.2000  0.0000  0.0142  0.0395  0.0276  0.0000  0.0000  4.0860  1.0056       0       4       6       5
5  高风险规则  MOB1 0+  未命中  0.2107  0.2058  0.1781  0.1989  1.0000  0.9858  0.9605  0.9724  1.0000  1.0144  0.8732  0.9998     356     277     146     176

### 4.1 多标签逾期分析

支持传入 `overdue` 与 `dpds` 生成多逾期标签策略表，再使用 `rule_strategy` 转换。

In [19]:
multi_report = rule1.report(
    df,
    target='target',
    overdue=['MOB1'],
    dpds=[7, 3, 0]
)
multi_report.head()

   分箱详情                                                     MOB1 7+                            ... MOB1 0+
   规则分类                               指标名称   分箱 样本总数   样本占比    好样本数  好样本占比 坏样本数  坏样本占比   坏样本率  ...    坏样本数  坏样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比    准确率    精确率    召回率   F1分数
0  验证规则  score_c3 < 500 & score_coral > 80   命中   15 0.0155       9 0.0109    6 0.0414 0.4000  ...       6 0.0302 0.4000 1.9497  0.0149  0.9647 0.7918 0.4000 0.0302 0.0561
1  验证规则  score_c3 < 500 & score_coral > 80  未命中  955 0.9845     816 0.9891  139 0.9586 0.1455  ...     193 0.9698 0.2021 0.9851 -0.9497 -0.9647 0.2082 0.2021 0.9698 0.3345

[2 rows x 41 columns]

In [20]:
# 多标签下的策略文档表
multi_target_table = rule_target_table(multi_report)
multi_target_table

                                规则详情     逾期指标 命中情况  样本总数   样本占比   坏样本率  LIFT值    坏账改善   风险拒绝比
0  score_c3 < 500 & score_coral > 80  MOB1 7+   命中    15 0.0155 0.4000 2.6759  0.0263  1.7022
1  score_c3 < 500 & score_coral > 80  MOB1 7+  未命中   955 0.9845 0.1455 0.9737 -1.6759 -1.7022
2  score_c3 < 500 & score_coral > 80  MOB1 7+   合计   970 1.0000 0.1495 1.0000  0.0000  0.0000
3  score_c3 < 500 & score_coral > 80  MOB1 3+   命中    15 0.0155 0.4000 2.3951  0.0219  1.4170
4  score_c3 < 500 & score_coral > 80  MOB1 3+  未命中   955 0.9845 0.1634 0.9781 -1.3951 -1.4170
5  score_c3 < 500 & score_coral > 80  MOB1 3+   合计   970 1.0000 0.1670 1.0000  0.0000  0.0000
6  score_c3 < 500 & score_coral > 80  MOB1 0+   命中    15 0.0155 0.4000 1.9497  0.0149  0.9647
7  score_c3 < 500 & score_coral > 80  MOB1 0+  未命中   955 0.9845 0.2021 0.9851 -0.9497 -0.9647
8  score_c3 < 500 & score_coral > 80  MOB1 0+   合计   970 1.0000 0.2052 1.0000  0.0000  0.0000

## 5. 生产规则流转一致性校验 (`RuleFlow`)

线上线下规则一致性校验时，生产规则通常按顺序执行。串行模式下，样本命中某条拒绝规则后不再继续流转；并行模式下，每条规则都会独立计算命中结果。

In [21]:
# 模拟生产拼表数据：如果第一条规则已经拒绝，后续规则变量可能为空
production_data = df.copy()
production_data.loc[production_data['score_c3'] < 500, 'score_coral'] = np.nan

prod_rules = [
    Rule("score_c3 < 500", name="低分拒绝"),
    Rule("score_coral > 85", name="高风险拒绝"),
    Rule("score_qingyun > 80", name="青云高风险拒绝"),
]

serial_flow = RuleFlow(prod_rules, mode="serial")
serial_pred = serial_flow.predict(production_data)
serial_pred.head()

    低分拒绝  高风险拒绝  青云高风险拒绝 命中规则序号     命中规则  是否命中   是否通过
0  False  False     True      3  青云高风险拒绝  True  False
1  False  False     True      3  青云高风险拒绝  True  False
2  False  False     True      3  青云高风险拒绝  True  False
3  False  False     True      3  青云高风险拒绝  True  False
4  False  False     True      3  青云高风险拒绝  True  False

In [22]:
# 串行报表：样本总数表示流转到该规则的样本数
serial_report = serial_flow.report(production_data)
serial_report

   规则序号     规则名称               规则表达式  样本总数  规则命中  命中率(绝对值)  命中率(相对值)  规则通过  通过率(绝对值)  通过率(相对值)
0     1     低分拒绝      score_c3 < 500   970    17    0.0175    0.0175   953    0.9825    0.9825
1     2    高风险拒绝    score_coral > 85   953   249    0.2567    0.2613   704    0.7258    0.7387
2     3  青云高风险拒绝  score_qingyun > 80   704   704    0.7258    1.0000     0    0.0000    0.0000

In [23]:
# 规则集整体通过/命中汇总
serial_summary = serial_flow.summary(production_data)
serial_summary

   样本总数  通过样本  命中样本    通过率    命中率
0   970     0   970 0.0000 1.0000

In [24]:
# 按放款月份 + 商品类别分组输出 report 和 summary
group_report = serial_flow.report(
    production_data,
    date_col="放款时间",
    freq="M",
    group_cols="商品类别",
)
group_summary = serial_flow.summary(
    production_data,
    date_col="放款时间",
    freq="M",
    group_cols="商品类别",
)

display(group_report.head(10))
display(group_summary.head(10))

      统计周期  商品类别  规则序号     规则名称               规则表达式  样本总数  规则命中  命中率(绝对值)  命中率(相对值)  规则通过  通过率(绝对值)  通过率(相对值)
0  2025-11  手机通讯     1     低分拒绝      score_c3 < 500    57     0    0.0000    0.0000    57    1.0000    1.0000
1  2025-11  手机通讯     2    高风险拒绝    score_coral > 85    57     0    0.0000    0.0000    57    1.0000    1.0000
2  2025-11  手机通讯     3  青云高风险拒绝  score_qingyun > 80    57    57    1.0000    1.0000     0    0.0000    0.0000
3  2025-11  珠宝首饰     1     低分拒绝      score_c3 < 500   290     0    0.0000    0.0000   290    1.0000    1.0000
4  2025-11  珠宝首饰     2    高风险拒绝    score_coral > 85   290     0    0.0000    0.0000   290    1.0000    1.0000
5  2025-11  珠宝首饰     3  青云高风险拒绝  score_qingyun > 80   290   290    1.0000    1.0000     0    0.0000    0.0000
6  2025-11  电脑数码     1     低分拒绝      score_c3 < 500     9     0    0.0000    0.0000     9    1.0000    1.0000
7  2025-11  电脑数码     2    高风险拒绝    score_coral > 85     9     0    0.0000    0.0000     9    1.0000    1.0000
8  2025-11  电脑数码     3  青云高风险拒绝  score_qingyun > 80     9     9    1.0000    1.0000     0    0.0000    0.0000
9  2025-12  家用电器     1     低分拒绝      score_c3 < 500     1     0    0.0000    0.0000     1    1.0000    1.0000

      统计周期  商品类别  样本总数  通过样本  命中样本    通过率    命中率
0  2025-11  手机通讯    57     0    57 0.0000 1.0000
1  2025-11  珠宝首饰   290     0   290 0.0000 1.0000
2  2025-11  电脑数码     9     0     9 0.0000 1.0000
3  2025-12  家用电器     1     0     1 0.0000 1.0000
4  2025-12  手机通讯    60     0    60 0.0000 1.0000
5  2025-12  珠宝首饰   202     0   202 0.0000 1.0000
6  2025-12  电脑数码    10     0    10 0.0000 1.0000
7  2025-12    礼包     8     0     8 0.0000 1.0000
8  2026-01  手机通讯    17     0    17 0.0000 1.0000
9  2026-01  珠宝首饰    71     0    71 0.0000 1.0000

In [25]:
# 并行模式：所有规则都对全量样本计算，适合排查单条规则本身的命中覆盖
parallel_flow = RuleFlow(prod_rules, mode="parallel")
parallel_pred = parallel_flow.predict(production_data)
parallel_report = parallel_flow.report(production_data)

display(parallel_pred.head())
parallel_report

    低分拒绝  高风险拒绝  青云高风险拒绝 命中规则序号     命中规则  是否命中   是否通过
0  False  False     True      3  青云高风险拒绝  True  False
1  False  False     True      3  青云高风险拒绝  True  False
2  False  False     True      3  青云高风险拒绝  True  False
3  False  False     True      3  青云高风险拒绝  True  False
4  False  False     True      3  青云高风险拒绝  True  False

   规则序号     规则名称               规则表达式  样本总数  规则命中  命中率(绝对值)  命中率(相对值)  规则通过  通过率(绝对值)  通过率(相对值)
0     1     低分拒绝      score_c3 < 500   970    17    0.0175    0.0175   953    0.9825    0.9825
1     2    高风险拒绝    score_coral > 85   970   249    0.2567    0.2567   721    0.7433    0.7433
2     3  青云高风险拒绝  score_qingyun > 80   970   970    1.0000    1.0000     0    0.0000    0.0000

### 5.1 线上线下命中差异对比

`RuleFlow.compare` 支持三类生产命中结果输入：命中规则名单列、通过 `hit_col` 指定的命中列，以及每条规则一列的 0/1 或 True/False 命中矩阵。返回值包含规则级一致性报告和差异订单明细。

In [26]:
# 方式一：线上生产结果是一列命中规则；元素可以是 rule.name、[rule.name]、[] 或空值
online_hits = pd.DataFrame({
    "线上命中规则": serial_pred["命中规则"].apply(lambda x: [x] if x else []),
}, index=production_data.index)

# 演示单个规则也可以直接传 rule.name 字符串
hit_rows = online_hits[online_hits["线上命中规则"].map(bool)].index
if len(hit_rows) > 1:
    online_hits.at[hit_rows[1], "线上命中规则"] = online_hits.at[hit_rows[1], "线上命中规则"][0]

# 人工制造一条差异，用于演示 diff_detail 输出
if len(hit_rows) > 0:
    online_hits.at[hit_rows[0], "线上命中规则"] = ["高风险拒绝"]

consistency_report, diff_detail = serial_flow.compare(
    production_data,
    online_hits,
    hit_col="线上命中规则",
)

display(consistency_report)
diff_detail[["线下命中规则", "线上命中规则", "差异规则", "线下独有规则", "线上独有规则"]].head()

   规则序号     规则名称               规则表达式  样本总数  一致样本  差异样本    一致率    差异率
0     1     低分拒绝      score_c3 < 500   970   970     0 1.0000 0.0000
1     2    高风险拒绝    score_coral > 85   970   969     1 0.9990 0.0010
2     3  青云高风险拒绝  score_qingyun > 80   970   969     1 0.9990 0.0010

    线下命中规则 线上命中规则           差异规则   线下独有规则 线上独有规则
0  青云高风险拒绝  高风险拒绝  高风险拒绝|青云高风险拒绝  青云高风险拒绝  高风险拒绝

In [27]:
# 方式二：线上结果是规则命中矩阵，列名为规则名称，值为 0/1 或 True/False
online_hit_matrix = serial_pred[[rule.name for rule in prod_rules]].fillna(False).astype(int)

# 人工制造一条矩阵差异
if len(online_hit_matrix) > 0:
    online_hit_matrix.iloc[0, online_hit_matrix.columns.get_loc("高风险拒绝")] = 1

matrix_report, matrix_diff = serial_flow.compare(production_data, online_hit_matrix)

display(matrix_report)
matrix_diff[["线下命中规则", "线上命中规则", "差异规则"]].head()

   规则序号     规则名称               规则表达式  样本总数  一致样本  差异样本    一致率    差异率
0     1     低分拒绝      score_c3 < 500   970   970     0 1.0000 0.0000
1     2    高风险拒绝    score_coral > 85   970   969     1 0.9990 0.0010
2     3  青云高风险拒绝  score_qingyun > 80   970   970     0 1.0000 0.0000

    线下命中规则         线上命中规则   差异规则
0  青云高风险拒绝  高风险拒绝|青云高风险拒绝  高风险拒绝

In [28]:
# 方式三：按订单号对齐。线上结果顺序可以与 data 不一致
production_data_with_order = production_data.copy()
production_data_with_order["订单号"] = [f"ORD{i:06d}" for i in range(len(production_data_with_order))]

online_hits_by_order = pd.DataFrame({
    "订单号": production_data_with_order["订单号"],
    "生产命中规则": serial_pred["命中规则"].apply(lambda x: [x] if x else []),
})
online_hits_by_order = online_hits_by_order.sample(frac=1, random_state=42).reset_index(drop=True)

order_report, order_diff = serial_flow.compare(
    production_data_with_order,
    online_hits_by_order,
    hit_col="生产命中规则",
    order_id_col="订单号",
)

display(order_report)
order_diff.head()

   规则序号     规则名称               规则表达式  样本总数  一致样本  差异样本    一致率    差异率
0     1     低分拒绝      score_c3 < 500   970   970     0 1.0000 0.0000
1     2    高风险拒绝    score_coral > 85   970   970     0 1.0000 0.0000
2     3  青云高风险拒绝  score_qingyun > 80   970   970     0 1.0000 0.0000

Empty DataFrame
Columns: [客户编号, 放款时间, 放款金额, 商品类别, MOB1, CURRENT_DPD, score_c3, score_coral, score_fraud, score_qingyun, score_zhanxin, 轻花老客海纳子分V1, 天创小额网贷分, 近六个月非银多头机构数, 手机号近一个月非银多头机构数, 身份证近一个月非银多头机构数, 衡枢鉴真分老客版, FPD, target, 订单号, 线下命中规则, 线上命中规则, 差异规则, 线下独有规则, 线上独有规则, 线下_低分拒绝, 线上_低分拒绝, 是否一致_低分拒绝, 线下_高风险拒绝, 线上_高风险拒绝, 是否一致_高风险拒绝, 线下_青云高风险拒绝, 线上_青云高风险拒绝, 是否一致_青云高风险拒绝]
Index: []

[0 rows x 34 columns]

## 5. 规则状态与异常 (RuleState / RuleStateError / RuleUnAppliedError)

`Rule` 内部维护状态机 `RuleState`（INITIALIZED→APPLIED）；在未 `predict` 前调用 `result()` 会抛出 `RuleUnAppliedError`，状态非法时抛出 `RuleStateError`。

In [29]:
from hscredit.core.rules import RuleState, RuleStateError, RuleUnAppliedError

# 规则状态枚举
print('RuleState 状态:', [s.name for s in RuleState])

# 未应用即取结果 -> 抛 RuleUnAppliedError
r_demo = Rule('score_c3 < 500', name='状态演示规则')
try:
    r_demo.result()
except RuleUnAppliedError as e:
    print('未 predict 取 result 触发 RuleUnAppliedError:', str(e))

# 正常流程：predict 后状态变为 APPLIED，可取 result
r_demo.predict(df)
print('predict 后命中数:', int(r_demo.result().sum()))
print('异常基类:', RuleStateError.__name__, '/', RuleUnAppliedError.__name__)

RuleState 状态: ['INITIALIZED', 'APPLIED']
未 predict 取 result 触发 RuleUnAppliedError: 规则尚未应用，请先调用 predict()
predict 后命中数: 17
异常基类: RuleStateError / RuleUnAppliedError