# 20 规则置入置出分析（rule_swap_analysis）

本示例围绕当前生产语义演示 `rule_swap_analysis`：阶段漏斗、独立/串行规则、
有偏样本通过率校准、实际/预测风险、金额、多逾期标签和多评分。

示例中的断言用于校验样本守恒、去重和展示顺序不改变结论。

## 1. 业务口径

分析按以下母集逐步推进：

1. 全量分析样本先剔除 `rules_base` 命中的 **OUT-OUT**（生产基础拒绝，与本次改规则无关）。
2. 剩余样本再剔除 `rules_out` 命中的 **IN-OUT**，得到本次分析的 `total通过样本`。
3. 只在 `total通过样本` 内执行 `rules_in`：命中为 **OUT-IN**，未命中为 **IN-IN**。
4. 置入后 **ALL-IN = IN-IN + OUT-IN = total通过样本**。

风险口径：OUT-IN 没有实际表现，使用评分分箱预测风险并应用 `out_in_uplift`；
其余原子客群使用实际标签。`risk_uplifts` 可选地让其他客群也应用上浮系数。

In [1]:
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append('..')

import numpy as np
import pandas as pd
from IPython.display import display

from hscredit.core.rules import Rule
from hscredit.report import feature_bin_stats, rule_swap_analysis

pd.set_option('display.max_columns', 30)
pd.set_option('display.width', 180)

## 2. 构造带表现的分析样本和历史参考样本

In [2]:
def make_credit_data(n, seed):
    rng = np.random.default_rng(seed)
    score_main = np.clip(rng.normal(630, 75, n), 350, 850)
    score_alt = np.clip(score_main + rng.normal(0, 35, n), 350, 850)
    income = np.clip(rng.lognormal(np.log(9000), 0.55, n), 1800, 50000)
    multihead = rng.poisson(5.5, n)
    fraud_score = rng.beta(2, 7, n)
    logit = (590 - score_main) / 65 + 0.11 * multihead + 1.4 * fraud_score - 1.0
    bad_probability = 1 / (1 + np.exp(-logit))
    target = rng.binomial(1, bad_probability)
    mob1 = np.where(
        target == 1,
        rng.choice([4, 8, 15, 35, 60], n),
        rng.choice([0, 0, 0, 1, 2, 4], n),
    )
    amount = np.round(np.clip(income * rng.uniform(0.25, 0.75, n), 1000, 30000), 2)
    approved_amount = np.where(
        rng.random(n) < 0.7,
        np.round(amount * rng.uniform(0.8, 1.15, n), 2),
        np.nan,
    )
    return pd.DataFrame({
        'score_main': score_main,
        'score_alt': score_alt,
        'income': income,
        'multihead': multihead,
        'fraud_score': fraud_score,
        'target': target,
        'MOB1': mob1,
        'amount': amount,
        'approved_amount': approved_amount,
    })


data = make_credit_data(900, seed=20260825)
reference_data = make_credit_data(2400, seed=20260824)

print(f"分析样本: {len(data):,}，实际坏样本率: {data['target'].mean():.2%}")
print(f"参考样本: {len(reference_data):,}，实际坏样本率: {reference_data['target'].mean():.2%}")

分析样本: 900，实际坏样本率: 36.44%
参考样本: 2,400，实际坏样本率: 36.17%

## 3. 定义生产基础拒绝、本次置出和本次置入规则

In [3]:
rules_base = [
    Rule('fraud_score >= 0.72', name='生产反欺诈拒绝'),
    Rule('multihead >= 14', name='生产极端多头拒绝'),
]
rules_out = [
    Rule('(score_main < 540) & (income < 8000)', name='置出低分低收入'),
    Rule('multihead >= 10', name='置出高多头'),
]
rules_in = [
    Rule('(score_main >= 560) & (score_main < 615) & (income >= 9000)', name='置入中分高收入'),
    Rule('(score_alt >= 575) & (score_alt < 625) & (multihead <= 4)', name='置入备评分稳定'),
]

score_bin_table = feature_bin_stats(
    reference_data,
    feature='score_main',
    target='target',
    method='quantile',
    max_n_bins=8,
    margins=True,
    n_jobs=1,
)

common = dict(
    data=data,
    score='score_main',
    rules_base=rules_base,
    rules_out=rules_out,
    rules_in=rules_in,
    bin_table=score_bin_table,
    target='target',
    n_jobs=1,
)

def run_swap(**overrides):
    params = dict(common)
    params.update(overrides)
    return rule_swap_analysis(**params)

## 4. 完整阶段漏斗：独立规则模式

In [4]:
result = run_swap(
    amount='amount',
    sample_survival_rate=0.63,
    out_in_uplift=2.0,
    rule_analysis_mode='independent',
)
pipeline = result['swap_pipeline']

view_columns = [
    '规则分类', '指标名称', '风险来源', '样本总数', '样本占比',
    '原始坏样本率', '调整后坏样本率', '生产通过率',
    '阶段前样本数', '阶段后样本数', '样本总额',
]
display(pipeline[[column for column in view_columns if column in pipeline.columns]])

         规则分类      指标名称       风险来源  样本总数   样本占比  原始坏样本率  调整后坏样本率   生产通过率  阶段前样本数  阶段后样本数         样本总额
0        全量样本            实际表现+评分预测   900 1.0000  0.3718   0.4548 63.0000     900     900 4582962.7300
1   OUT-OUT拒绝   生产反欺诈拒绝       实际表现     1 0.0011  1.0000   1.0000 62.9300     900     899    5074.9500
2   OUT-OUT拒绝  生产极端多头拒绝       实际表现     1 0.0011  0.0000   0.0000 62.9300     900     899    2418.7000
3   OUT-OUT拒绝        合计       实际表现     2 0.0022  0.5000   0.5000 62.8600     900     898    7493.6500
4        剩余样本            实际表现+评分预测   898 0.9978  0.3715   0.4547 62.8600     898     898 4575469.0800
5    IN-OUT置出   置出低分低收入       实际表现    43 0.0478  0.6977   0.6977 59.8500     898     855  131534.5800
6    IN-OUT置出     置出高多头       实际表现    47 0.0522  0.4043   0.4043 59.5700     898     851  280410.3000
7    IN-OUT置出        合计       实际表现    87 0.0967  0.5287   0.5287 56.7700     898     811  402855.9900
8   total通过样本            实际表现+评分预测   811 0.9011  0.3547   0.4467 56.7700     811     811 4172613.0900
9     IN-IN通过                 实际表现   650 0.7222  0.3277   0.3277 45.5000     811     650 3161301.3200
10   OUT-IN置入   置入中分高收入       评分预测   111 0.1233  0.5008   1.0016 53.2700     650     761  804929.2400
11   OUT-IN置入   置入备评分稳定       评分预测    74 0.0822  0.4114   0.8227 50.6800     650     724  383404.0600
12   OUT-IN置入        合计       评分预测   161 0.1789  0.4637   0.9273 56.7700     650     811 1011311.7700
13   ALL-IN置换            实际表现+评分预测   811 0.9011  0.3547   0.4467 56.7700     811     811 4172613.0900

In [5]:
def stage_row(frame, category):
    rows = frame[frame['规则分类'] == category]
    totals = rows[rows['指标名称'].fillna('') == '合计']
    return (totals if not totals.empty else rows).iloc[-1]


base_mask = np.logical_or.reduce([rule.predict(data).to_numpy() for rule in rules_base])
after_base = ~base_mask
out_mask = after_base & np.logical_or.reduce([rule.predict(data).to_numpy() for rule in rules_out])
total_mask = after_base & ~out_mask
in_mask = total_mask & np.logical_or.reduce([rule.predict(data).to_numpy() for rule in rules_in])
in_in_mask = total_mask & ~in_mask

assert stage_row(pipeline, 'OUT-OUT拒绝')['样本总数'] == int(base_mask.sum())
assert stage_row(pipeline, 'IN-OUT置出')['样本总数'] == int(out_mask.sum())
assert stage_row(pipeline, 'total通过样本')['样本总数'] == int(total_mask.sum())
assert stage_row(pipeline, 'OUT-IN置入')['样本总数'] == int(in_mask.sum())
assert stage_row(pipeline, 'IN-IN通过')['样本总数'] == int(in_in_mask.sum())
assert stage_row(pipeline, 'ALL-IN置换')['样本总数'] == int(total_mask.sum())
assert int(base_mask.sum() + out_mask.sum() + in_in_mask.sum() + in_mask.sum()) == len(data)

print('样本守恒检查通过：OUT-OUT + IN-OUT + IN-IN + OUT-IN = 全量样本')

样本守恒检查通过：OUT-OUT + IN-OUT + IN-IN + OUT-IN = 全量样本

## 5. 置换前后汇总与展示顺序不变性

In [6]:
display(result['swap_result'])

reverse_result = run_swap(
    amount='amount',
    sample_survival_rate=0.63,
    reverse_order=True,
)
pd.testing.assert_frame_equal(result['swap_result'], reverse_result['swap_result'])
print('reverse_order 只改变流水线展示顺序，不改变 swap_result。')

        指标     变化前     变化后    绝对变化   相对变化
0      通过率 45.5000 56.7700 11.2700 0.2477
1      逾期率  0.3277  0.4467  0.1190 0.3633
2   风险上浮系数  1.0000  1.2595  0.2595 0.2595
3  样本集幸存比例  0.6300  0.6300  0.0000 0.0000

reverse_order 只改变流水线展示顺序，不改变 swap_result。

## 6. 同一步内的独立与串行规则

- `independent`：每条规则都基于所属阶段的同一父样本执行；规则明细允许重复命中，阶段“合计”按并集去重。
- `sequential`：同一阶段内逐条漏样本，后一条规则承接前一条规则处理后的状态。

In [7]:
independent = run_swap(rule_analysis_mode='independent')['swap_pipeline']
sequential = run_swap(rule_analysis_mode='sequential')['swap_pipeline']

compare_columns = ['规则分类', '指标名称', '样本总数', '阶段前样本数', '阶段后样本数']
print('独立模式：')
display(independent.loc[independent['规则分类'] == 'OUT-IN置入', compare_columns])
print('串行模式：')
display(sequential.loc[sequential['规则分类'] == 'OUT-IN置入', compare_columns])

ind_rows = independent[
    (independent['规则分类'] == 'OUT-IN置入')
    & (independent['指标名称'].fillna('') != '合计')
]
seq_rows = sequential[
    (sequential['规则分类'] == 'OUT-IN置入')
    & (sequential['指标名称'].fillna('') != '合计')
]
assert ind_rows['样本总数'].sum() >= stage_row(independent, 'OUT-IN置入')['样本总数']
assert seq_rows['样本总数'].sum() == stage_row(sequential, 'OUT-IN置入')['样本总数']

独立模式：

        规则分类     指标名称  样本总数  阶段前样本数  阶段后样本数
10  OUT-IN置入  置入中分高收入   111     650     761
11  OUT-IN置入  置入备评分稳定    74     650     724
12  OUT-IN置入       合计   161     650     811

串行模式：

        规则分类     指标名称  样本总数  阶段前样本数  阶段后样本数
10  OUT-IN置入  置入中分高收入   111     650     761
11  OUT-IN置入  置入备评分稳定    50     761     811
12  OUT-IN置入       合计   161     650     811

## 7. 有偏分析样本的生产通过率校准

`sample_survival_rate` 是“分析样本在生产全量进件中的幸存比例”，必须位于 `(0, 1]`。
它只校准生产通过率漏斗，不改写本次样本的命中数、坏样本率或置换结论。

In [8]:
full_sample = run_swap(sample_survival_rate=1.0)['swap_pipeline']
biased_sample = run_swap(sample_survival_rate=0.63)['swap_pipeline']

calibration = pd.DataFrame({
    '阶段': biased_sample['规则分类'],
    '分析样本数': biased_sample['样本总数'],
    '全量样本假设_生产通过率': full_sample['生产通过率'],
    '幸存率63%_生产通过率': biased_sample['生产通过率'],
})
display(calibration)

assert biased_sample.iloc[0]['生产通过率'] == 63.0
assert np.array_equal(full_sample['样本总数'].to_numpy(), biased_sample['样本总数'].to_numpy())

           阶段  分析样本数  全量样本假设_生产通过率  幸存率63%_生产通过率
0        全量样本    900      100.0000       63.0000
1   OUT-OUT拒绝      1       99.8889       62.9300
2   OUT-OUT拒绝      1       99.8889       62.9300
3   OUT-OUT拒绝      2       99.7778       62.8600
4        剩余样本    898       99.7778       62.8600
5    IN-OUT置出     43       95.0000       59.8500
6    IN-OUT置出     47       94.5556       59.5700
7    IN-OUT置出     87       90.1111       56.7700
8   total通过样本    811       90.1111       56.7700
9     IN-IN通过    650       72.2222       45.5000
10   OUT-IN置入    111       84.5556       53.2700
11   OUT-IN置入     74       80.4444       50.6800
12   OUT-IN置入    161       90.1111       56.7700
13   ALL-IN置换    811       90.1111       56.7700

## 8. 实际风险、预测风险与可选客群上浮

In [9]:
risk_view = pipeline.loc[
    pipeline['规则分类'].isin(['OUT-OUT拒绝', 'IN-OUT置出', 'IN-IN通过', 'OUT-IN置入']),
    ['规则分类', '指标名称', '风险来源', '原始坏样本数', '调整后坏样本数',
     '原始坏样本率', '调整后坏样本率'],
]
display(risk_view)

out_in_total = stage_row(pipeline, 'OUT-IN置入')
assert '评分预测' in out_in_total['风险来源']
assert out_in_total['调整后坏样本数'] >= out_in_total['原始坏样本数']

uplifted = run_swap(risk_uplifts={'in_in': 1.15})['swap_pipeline']
in_in = stage_row(uplifted, 'IN-IN通过')
assert np.isclose(in_in['调整后坏样本数'], in_in['原始坏样本数'] * 1.15)
display(uplifted.loc[uplifted['规则分类'] == 'IN-IN通过',
                     ['规则分类', '风险来源', '原始坏样本数', '调整后坏样本数']])

         规则分类      指标名称  风险来源   原始坏样本数  调整后坏样本数  原始坏样本率  调整后坏样本率
1   OUT-OUT拒绝   生产反欺诈拒绝  实际表现   1.0000   1.0000  1.0000   1.0000
2   OUT-OUT拒绝  生产极端多头拒绝  实际表现   0.0000   0.0000  0.0000   0.0000
3   OUT-OUT拒绝        合计  实际表现   1.0000   1.0000  0.5000   0.5000
5    IN-OUT置出   置出低分低收入  实际表现  30.0000  30.0000  0.6977   0.6977
6    IN-OUT置出     置出高多头  实际表现  19.0000  19.0000  0.4043   0.4043
7    IN-OUT置出        合计  实际表现  46.0000  46.0000  0.5287   0.5287
9     IN-IN通过            实际表现 213.0000 213.0000  0.3277   0.3277
10   OUT-IN置入   置入中分高收入  评分预测  55.5900 111.1801  0.5008   1.0016
11   OUT-IN置入   置入备评分稳定  评分预测  30.4400  60.8800  0.4114   0.8227
12   OUT-IN置入        合计  评分预测  74.6501 149.3001  0.4637   0.9273

      规则分类  风险来源   原始坏样本数  调整后坏样本数
9  IN-IN通过  实际表现 213.0000 244.9500

## 9. 金额口径与 OUT-IN 额度回填

In [10]:
amount_result = run_swap(
    amount='amount',
    out_in_amount_col='approved_amount',
    out_in_amount_fill=3000.0,
)['swap_pipeline']

amount_columns = [
    '规则分类', '指标名称', '样本总数', '样本总额',
    '原始坏样本金额', '调整后坏样本金额', '金额坏样本率',
]
display(amount_result[[column for column in amount_columns if column in amount_result.columns]])
assert stage_row(amount_result, 'OUT-IN置入')['样本总额'] > 0

         规则分类      指标名称  样本总数         样本总额
0        全量样本             900 4570522.1400
1   OUT-OUT拒绝   生产反欺诈拒绝     1    5074.9500
2   OUT-OUT拒绝  生产极端多头拒绝     1    2418.7000
3   OUT-OUT拒绝        合计     2    7493.6500
4        剩余样本             898 4563028.4900
5    IN-OUT置出   置出低分低收入    43  131534.5800
6    IN-OUT置出     置出高多头    47  280410.3000
7    IN-OUT置出        合计    87  402855.9900
8   total通过样本             811 4160172.5000
9     IN-IN通过             650 3161301.3200
10   OUT-IN置入   置入中分高收入   111  799539.9300
11   OUT-IN置入   置入备评分稳定    74  376267.8300
12   OUT-IN置入        合计   161  998871.1800
13   ALL-IN置换             811 4160172.5000

## 10. 多逾期标签：MOB1 的 DPD7 / DPD3 / DPD0

In [11]:
multi_label_bins = feature_bin_stats(
    reference_data,
    feature='score_main',
    overdue='MOB1',
    dpds=[7, 3, 0],
    method='quantile',
    max_n_bins=8,
    margins=True,
    n_jobs=1,
)
multi_label_result = rule_swap_analysis(
    data=data,
    score='score_main',
    rules_base=rules_base,
    rules_out=rules_out,
    rules_in=rules_in,
    bin_table=multi_label_bins,
    overdue='MOB1',
    dpds=[7, 3, 0],
    n_jobs=1,
)

multi_pipeline = multi_label_result['swap_pipeline']
display(multi_pipeline)
assert isinstance(multi_pipeline.columns, pd.MultiIndex)
assert {'MOB1_7+', 'MOB1_3+', 'MOB1_0+'}.issubset(set(multi_pipeline.columns.get_level_values(0)))
assert multi_pipeline[('MOB1_7+', '调整后坏样本率')].max() > 0

         分箱详情                                                                                                                                                                 MOB1_7+  ...    MOB1_0+
         规则分类      指标名称                                                         规则详情   行类型 样本总数   样本占比 阶段前样本数 阶段后样本数 阶段前生产通过率    生产通过率      通过率 通过率(绝对值) 通过率(相对值)    通过率变化       风险来源  ...       风险来源   原始好样本数  调整后好样本数     好样本数   好样本占比     坏样本数  坏样本占比   坏样本率   原始坏样本数 原始坏样本率  调整后坏样本数 调整后坏样本率  LIFT值    坏账改善     风险拒绝比
0        全量样本                                                                           状态  900 1.0000    900    900 100.0000 100.0000 100.0000 100.0000   0.0000   0.0000  实际表现+评分预测  ...  实际表现+评分预测 279.5367 158.0734 158.0734  0.1756 741.9266 0.8244 0.8244 620.4633 0.6894 741.9266  0.8244 1.0000  0.0000    0.0000
1   OUT-OUT拒绝   生产反欺诈拒绝                                          fraud_score >= 0.72  规则明细    1 0.0011    900    899 100.0000  99.8889  99.8889  99.8889  -0.0011  -0.1111       实际表现  ...       实际表现   0.0000   0.0000   0.0000  0.0000   1.0000 1.0000 1.0000   1.0000 1.0000   1.0000  1.0000 1.2131 -0.2131 -191.7522
2   OUT-OUT拒绝  生产极端多头拒绝                                              multihead >= 14  规则明细    1 0.0011    900    899 100.0000  99.8889  99.8889  99.8889  -0.0011  -0.1111       实际表现  ...       实际表现   1.0000   1.0000   1.0000  1.0000   0.0000 0.0000 0.0000   0.0000 0.0000   0.0000  0.0000 0.0000  1.0000  900.0000
3   OUT-OUT拒绝        合计                                                               阶段合计    2 0.0022    900    898 100.0000  99.7778  99.7778  99.7778  -0.0022  -0.2222       实际表现  ...       实际表现   1.0000   1.0000   1.0000  0.5000   1.0000 0.5000 0.5000   1.0000 0.5000   1.0000  0.5000 0.6065  0.3935  177.0620
4        剩余样本                                                                           状态  898 0.9978    898    898  99.7778  99.7778  99.7778  99.7778   0.0000   0.0000  实际表现+评分预测  ...  实际表现+评分预测 278.5367 157.0734 157.0734  0.1749 740.9266 0.8251 0.8251 619.4633 0.6898 740.9266  0.8251 1.0009 -0.0009   -0.0009
5    IN-OUT置出   置出低分低收入                         (score_main < 540) & (income < 8000)  规则明细   43 0.0478    898    855  99.7778  95.0000  95.0000  95.0000  -0.0479  -4.7778       实际表现  ...       实际表现   8.0000   8.0000   8.0000  0.1860  35.0000 0.8140 0.8140  35.0000 0.8140  35.0000  0.8140 0.9874  0.0126    0.2643
6    IN-OUT置出     置出高多头                                              multihead >= 10  规则明细   47 0.0522    898    851  99.7778  94.5556  94.5556  94.5556  -0.0523  -5.2222       实际表现  ...       实际表现  15.0000  15.0000  15.0000  0.3191  32.0000 0.6809 0.6809  32.0000 0.6809  32.0000  0.6809 0.8259  0.1741    3.3336
7    IN-OUT置出        合计                                                               阶段合计   87 0.0967    898    811  99.7778  90.1111  90.1111  90.1111  -0.0969  -9.6667       实际表现  ...       实际表现  23.0000  23.0000  23.0000  0.2644  64.0000 0.7356 0.7356  64.0000 0.7356  64.0000  0.7356 0.8924  0.1076    1.1135
8   total通过样本                                                                           状态  811 0.9011    811    811  90.1111  90.1111  90.1111  90.1111   0.0000   0.0000  实际表现+评分预测  ...  实际表现+评分预测 255.5367 134.0734 134.0734  0.1653 676.9266 0.8347 0.8347 555.4633 0.6849 676.9266  0.8347 1.0125 -0.0125   -0.0139
9     IN-IN通过                                                                           状态  650 0.7222    811    650  90.1111  72.2222  72.2222  72.2222  -0.1985 -17.8889       实际表现  ...       实际表现 216.0000 216.0000 216.0000  0.3323 434.0000 0.6677 0.6677 434.0000 0.6677 434.0000  0.6677 0.8099  0.1901    0.2631
10   OUT-IN置入   置入中分高收入  (score_main >= 560) & (score_main < 615) & (income >= 9000)  规则明细  111 0.1233    650    761  72.2222  84.5556  84.5556  84.5556   0.1708  12.3333       评分预测  ...       评分预测  25.2334 -60.5333 -60.5333 -0.5453 171.5333 1.5453 1.5453  85.7666 0.7727 171.5333  1.5453 1.8746 -0.8746   -7.0913
11   OUT-IN置入   置入备评分稳定    (score_alt >= 575) & (score_alt < 625) & (multihead <= 4)  规则明细   74 0.0822    650    724  72.2222  80.4444  80.4444  80.4444   0.1138   8.2222       评分预测  ...       评分预测  20.0833 -33.8333 -33.8333 -0.4572 107.8333 1.4572 1.4572  53.9167 0.7286 107.8333  1.4572 1.7677 -0.7677   -9.3366
12   OUT-IN置入        合计                                                               阶段合计  161 0.1789    650    811  72.2222  90.1111  90.1111  90.1111   0.2477  17.8889       评分预测  ...       评分预测  39.5367 -81.9266 -81.9266 -0.5089 242.9266 1.5089 1.5089 121.4633 0.7544 242.9266  1.5089 1.8303 -0.8303   -4.6416
13   ALL-IN置换                                                                           状态  811 0.9011    811    811  90.1111  90.1111  90.1111  90.1111   0.0000   0.0000  实际表现+评分预测  ...  实际表现+评分预测 255.5367 134.0734 134.0734  0.1653 676.9266 0.8347 0.8347 555.4633 0.6849 676.9266  0.8347 1.0125 -0.0125   -0.0139

[14 rows x 59 columns]

## 11. 多评分：每个评分必须有独立分箱表

In [12]:
score_map = {'主评分': 'score_main', '备评分': 'score_alt'}
score_bins = {
    name: feature_bin_stats(
        reference_data,
        feature=column,
        target='target',
        method='quantile',
        max_n_bins=8,
        margins=True,
        n_jobs=1,
    )
    for name, column in score_map.items()
}

multi_score_result = rule_swap_analysis(
    data=data,
    score=score_map,
    score_weights={'主评分': 0.7, '备评分': 0.3},
    rules_base=rules_base,
    rules_out=rules_out,
    rules_in=rules_in,
    bin_table=score_bins,
    target='target',
    n_jobs=1,
)
display(multi_score_result['swap_result'])
assert set(multi_score_result) == {'swap_pipeline', 'swap_result'}
assert stage_row(multi_score_result['swap_pipeline'], 'ALL-IN置换')['样本总数'] == int(total_mask.sum())

        指标     变化前     变化后    绝对变化   相对变化
0      通过率 72.2222 90.1111 17.8889 0.2477
1      逾期率  0.3277  0.4462  0.1185 0.3616
2   风险上浮系数  1.0000  1.2589  0.2589 0.2589
3  样本集幸存比例  1.0000  1.0000  0.0000 0.0000

## 12. 使用要点

- 分析数据即使是有偏样本，非 OUT-IN 客群仍必须带实际 `target` 或 `overdue` 表现；不能用参考样本标签替代。
- `reference_data` 用于训练评分到风险的映射；显式传 `bin_table` 时，多评分键必须与 `score` 字典完全一致。
- 独立模式看单规则边际覆盖，阶段合计看规则并集；串行模式看真实逐步漏斗。
- `reverse_order` 仅用于展示，不能改变 `swap_result`。
- 使用 `out_in_amount_col` 或 `out_in_amount_fill` 时必须同时传入 `amount`。